### ISSUE TITLE
Allow recipes to include amounts of ingredients

### ISSUE THREAD

**Issue by RaymondWise** [RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator#13]
Must be done prior to https://github.com/RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator/issues/12

Rework the meal sheet structure

**Comment by RaymondWise** [comment]
I'm thinking the best structure for this would be three or 4 columns -

1. Meal name, repeated for each ingredient
2. Ingredient name
3. Ingredient amount
4. (Ingredient unit?)

e.g.

     BLT Pita | Pita Pocket | 1
     BLT Pita | Bacon       | 1
     BLT Pita | Lettuce     | 1
     BLT Pita | Tomato      | 1

The drawbacks here being: 

- Do I need one entire tomato for this? **Yes**, I can't buy part of a tomato.
- Do I need more than one tomato? **Depends** on how many slices you use and how many times this meal appears on the sheet

**Comment by RaymondWise** [comment]
I did some work on a copy of one of the recipe sheets and this will reorganize the list, but the amounts will need to be filled in separately

```
Option Explicit

Sub ReWorkIngredients()
    Dim targetSheet As Worksheet
    Set targetSheet = StructureTest
    Dim lastRow As Long
    lastRow = targetSheet.Cells(targetSheet.Rows.Count, 1).End(xlUp).Row
    Dim rowIndex As Long
    Dim columnIndex As Long
    Dim mealName As String
    Dim ingredientName As String
    Dim lastColumn As Long
    With targetSheet
        For rowIndex = lastRow To 1 Step -1
            lastColumn = .Cells(rowIndex, .Columns.Count).End(xlToLeft).Column
            If lastColumn > 2 Then
                mealName = .Cells(rowIndex, 1)
                For columnIndex = 3 To lastColumn
                    ingredientName = .Cells(rowIndex, columnIndex)
                    .Cells(rowIndex, columnIndex).Clear
                    .Rows(rowIndex + 1).Insert shift:=xlShiftDown
                    .Cells(rowIndex + 1, 1) = mealName
                    .Cells(rowIndex + 1, 2) = ingredientName
                Next
            End If
        Next
    End With
End Sub  
```

**Comment by JRated** [comment]
Ray i think you should focus less on parts/wholes of items and more just on tracking a single weight measurement, say grams for example. That way if every recipe had a different gram requirement for tomatoes (for example), and several recipes require tomatoes, you end up with a totalled gram amount 1120g Tomato for example. Then when shopping at the store you can just look at the package and work out how many you need. Seems to me like having a universal measurement system would make life easier when adding them all together

**Comment by RaymondWise** [comment]
@JRated that's a really good point.

**Comment by RaymondWise** [comment]
However, sometimes ingredients are in oz (liquid) vs oz (solid) or (volume vs weight). The conversion of these are different to grams, I think.

Maybe I'm way ahead of myself..

(U.S.) teaspoon, tablespoon, cup, ounce, pint, quart, gallon, pound
vs
(metric) grams, liters

Obviously metric is the way to go, but allowing conversion may need to be included. But then, again, US vs UK vs AUS are different from one another as well.

---------------
Everything must be standardized on the recipe sheet if the collection of values is going to happen properly, obviously. However, can you have liters and grams of something? I'm no chef, but I imagine something like flour *could* be in either.

**Comment by RaymondWise** [comment]
Now meal sheets have a new structure of

     Meal
           Ingredient  |  Quantity
           Ingredient  |  Quantity
